site_name: Community operators pipeline admin
repo_name: community-operators-pipeline
repo_url: https://github.com/redhat-openshift-ecosystem/community-operators-pipeline
nav:
  - "Overview": README.md
  - "Project":
      - "Overview": project-overview.md
      - "Create": project-create.md
      - "Maintain": project-maintain.md
      - "Develop": project-development.md

extra:
  version: 0.1

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mermaid2
  - macros

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.tabbed
  - attr_list
  - toc:
      toc_depth: 2
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
