production:
  type: ocp
  bundle:
    registry: quay.io
    organization: community-operators-pipeline
  index:
    registry: quay.io
    organization: community-operators-pipeline
    name: catalog_tmp
    tags:
      - v4.6-db
      - v4.7-db
      - v4.8-db
      - v4.9-db
      - v4.10-db
      - v4.11
    latest: ""
    signature:
      enabled: 1
      alias: quay.io/community-operators-pipeline/catalog
      endpoint: https://community-signing-pipeline-dev.apps.pipelines-stage.0ce8.p1.openshiftapps.com
  mirror:
    enabled: 1
    multiarch: 
      base: registry.redhat.io/openshift4/ose-operator-registry
      base_tags:
        - v4.5
        - v4.6
        - v4.7
        - v4.8
        - v4.9
        - v4.10
        - v4.11
      postfix: s
    registry: quay.io
    organization: community-operators-pipeline
    name: catalog
    username:
      in: mavala
      out: mavala
  test:
    force_deploy_openshift_version: "4.8"
    installation_skip:
      - ack-
      - apicurito

pipeline:
  base: https://github.com
  repo: redhat-openshift-ecosystem/community-operators-pipeline
  branch: main
  ci_scripts_dir: https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/dev/ci/scripts
  image: quay.io/operator_testing/operator-test-playbooks:dev
  playbooks:
    repo: https://github.com/redhat-openshift-ecosystem/operator-test-playbooks
    branch: "upstream-community-dev"
  automerge:
    enabled: 1
  reviewers:
    enabled: 0
  notifications:
    slack: 0
operatorhubio:
  enabled: 0
  registry: quay.io
  organization: operator-framework
  name: upstream-community-operators
  tag: latest


#base:
#  organisation: operator-framework
#  project: operator-test-playbooks
#  tag: master
tools:
  kind_version: v0.14.0
  kind_kube_version: v1.21.1
  operator_sdk_version: v1.8.0
