name: Operator release 
on:
  push:
    branches:
      - master
      - main

  workflow_dispatch:
    inputs:
      release:
        description: 'Force to run release'
        required: true
        default: '0'   
      delete:
        description: 'Remove operator virtually from git (cockroachdb or cockroachdb/5.0.4) for debuging only'
        required: false
        default: ''

env:
  OPP_DEBUG: 1
  OPP_CONTAINER_OPT: "-t"
  OPP_SCRIPT_URL: "https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/dev/ci/scripts/opp.sh"
  OPP_SCRIPT_ENV_URL: "https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/dev/ci/scripts/opp-env.sh"
  OPP_SCRIPT_ISS_URL: "https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/dev/ci/scripts/opp-iss.sh"
  OPP_SCRIPT_CLEANUP_URL: "https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/dev/ci/scripts/opp-disk-cleanup-on-startup.sh"
  OPP_SCRIPT_TRIGGER_OHIO_URL: "https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/dev/ci/scripts/opp-trigger-operatorhubio-ci.sh"
  OPP_IMAGE: "quay.io/operator_testing/operator-test-playbooks:dev"
  OPP_ANSIBLE_PULL_REPO: "https://github.com/redhat-openshift-ecosystem/operator-test-playbooks"
  OPP_ANSIBLE_PULL_BRANCH: "upstream-community-dev"
  OPP_PROD: 1
  OPP_MIRROR_LATEST_TAG: ""
  OPP_PRODUCTION_TYPE: "ocp"
  OPP_RELEASE_BUNDLE_REGISTRY: "quay.io"
  OPP_RELEASE_BUNDLE_ORGANIZATION: "community-operators-pipeline"
  OPP_RELEASE_INDEX_REGISTRY: "quay.io"
  OPP_RELEASE_INDEX_ORGANIZATION: "community-operators-pipeline"
  OPP_RELEASE_INDEX_NAME: "catalog_tmp"
  OPP_MIRROR_INDEX_REGISTRY: "quay.io"
  OPP_MIRROR_INDEX_ORGANIZATION: "community-operators-pipeline"
  OPP_MIRROR_INDEX_NAME: "catalog"
  OPP_MIRROR_INDEX_ENABLED: "1"
  OPP_MIRROR_INDEX_MULTIARCH_BASE: "registry.redhat.io/openshift4/ose-operator-registry"
  OPP_MULTIARCH_SUPPORTED_VERSIONS: "v4.5 v4.6 v4.7 v4.8 v4.9"
  OPP_MIRROR_INDEX_MULTIARCH_POSTFIX: "s"
  IIB_INPUT_REGISTRY_USER: "mavala"
  OPP_REGISTRY_MIRROR_USER: "mavala"
  OPP_THIS_REPO_BASE: "https://github.com"
  OPP_THIS_REPO: "redhat-openshift-ecosystem/community-operators-pipeline"
  OPP_THIS_BRANCH: "main"
  OPP_REVIEWERS_ENABLED: 0


  OPP_ALLOW_FORCE_RELEASE: ${{ github.event.inputs.release }}
  OPP_REMOVE_OPERATOR_AFTER_CLONE_PATH: "${{ github.event.inputs.delete }}"
  REGISTRY_RELEASE_API_TOKEN: ${{ secrets.REGISTRY_RELEASE_API_TOKEN }}
  REGISTRY_MIRROR_PW: ${{ secrets.REGISTRY_MIRROR_PW }}
  GODEBUG: x509ignoreCN=0
  CI_OHIO_TRIGGER_TOKEN: ${{ secrets.CI_OHIO_TRIGGER_TOKEN }}
  OHIO_REGISTRY_TOKEN: ${{ secrets.OHIO_REGISTRY_TOKEN }}
  QUAY_APPREG_TOKEN: ${{ secrets.QUAY_APPREG_TOKEN }}
  QUAY_COURIER_TOKEN: ${{ secrets.QUAY_COURIER_TOKEN }}
  REPO_GHA_PAT: ${{ secrets.REPO_GHA_PAT }}

jobs:
  release-ocp:
    name: "Index / ocp"

    runs-on: ubuntu-latest
    strategy:
      matrix:
        index-tag: ['v4.6-db', 'v4.7-db', 'v4.8-db', 'v4.9-db', 'v4.10-rcdb', 'v4.11-rc']

      fail-fast: false
    steps:

      - name: Prepare variables for the sign process
        id: openshift-vars
        env:
          #OPERATOR_INDEX_TAG_RAW: ${{ matrix.index-tag }}
          OPERATOR_INDEX_TAG_RAW: "v4.7-db"
          #OPP_AUTO_PACKAGEMANIFEST_CLUSTER_VERSION_LABEL: "${{ needs.pr-check.outputs.opp_auto_packagemanifest_cluster_version_label }}"
        run: |
          docker login ${OPP_MIRROR_INDEX_REGISTRY} -u $OPP_REGISTRY_MIRROR_USER -p $REGISTRY_MIRROR_PW
          OPERATOR_INDEX_TAG=$(echo ${OPERATOR_INDEX_TAG_RAW} |cut -d'-' -f1)
          skopeo inspect docker://${OPP_MIRROR_INDEX_REGISTRY}/${OPP_MIRROR_INDEX_ORGANIZATION}/${OPP_MIRROR_INDEX_NAME}:${OPERATOR_INDEX_TAG} > /dev/null # error out if needed
          OPERATOR_INDEX_DIGEST=$(skopeo inspect docker://${OPP_MIRROR_INDEX_REGISTRY}/${OPP_MIRROR_INDEX_ORGANIZATION}/${OPP_MIRROR_INDEX_NAME}:${OPERATOR_INDEX_TAG} | jq -r ".Digest")
          OPERATOR_INDEX_RESOLVED="${OPP_MIRROR_INDEX_REGISTRY}/${OPP_MIRROR_INDEX_ORGANIZATION}/${OPP_MIRROR_INDEX_NAME}@${OPERATOR_INDEX_DIGEST}"
          #OPERATOR_INDEX="${OPP_MIRROR_INDEX_REGISTRY}/${OPP_MIRROR_INDEX_ORGANIZATION}/${OPP_MIRROR_INDEX_NAME}:${OPERATOR_INDEX_TAG}"
          OPERATOR_INDEX="registry.redhat.io/redhat/community-operator-index:${OPERATOR_INDEX_TAG}"
          echo $OPERATOR_INDEX_RESOLVED
          echo $OPERATOR_INDEX
          echo $OPERATOR_INDEX_DIGEST
          echo "::set-output name=operator_index_resolved::${OPERATOR_INDEX_RESOLVED}"
          echo "::set-output name=operator_index::${OPERATOR_INDEX}"
          echo "::set-output name=operator_index_digest::${OPERATOR_INDEX_DIGEST}"
      
      
      - name: Check payload
        run: |
          echo "{\"manifest_digest\": \"${{ steps.openshift-vars.outputs.operator_index_digest }}\", \"reference\": \"${{ steps.openshift-vars.outputs.operator_index }}\",\"requester\": \"${{ secrets.SIGNATURE_WEBHOOK_REQUESTER_EMAIL }}\"}"

      
      
      
      - name: Initialize sign process
        uses: operator-framework/community-operators@webhook
        continue-on-error: true
        env:
          INDEX_SHA: "${{ steps.openshift-vars.outputs.index_sha }}"
          webhook_type: 'json-extended'
          webhook_url: 'https://community-signing-pipeline-dev.apps.pipelines-stage.0ce8.p1.openshiftapps.com'
          webhook_secret: ${{ secrets.SIGNATURE_WEBHOOK_SECRET }}
          data: "{\"manifest_digest\": \"${{ steps.openshift-vars.outputs.operator_index_digest }}\", \"reference\": \"${{ steps.openshift-vars.outputs.operator_index }}\",\"requester\": \"${{ secrets.SIGNATURE_WEBHOOK_REQUESTER_EMAIL }}\"}"
          webhook_auth: "community-op-cert:${{ secrets.SIGNATURE_WEBHOOK_PASSWD }}"

  