
name: Operator release

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
    inputs:
      release:
        description: 'Force to run release'
        required: true
        default: '0'
      delete:
        description: 'Delete operator (cockroachdb or cockroachdb/5.0.4) for debuging only'
        required: false
        default: ''

env:
  OPP_DEBUG: 1
  OPP_CONTAINER_OPT: "-t"
  OPP_SCRIPT_URL: "https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/dev/ci/scripts/opp.sh"
  OPP_SCRIPT_ENV_URL: "https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/dev/ci/scripts/opp-env.sh"
  OPP_SCRIPT_ISS_URL: "https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/dev/ci/scripts/opp-iss.sh"
  OPP_SCRIPT_CLEANUP_URL: "https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/dev/ci/scripts/opp-disk-cleanup-on-startup.sh"
  OPP_SCRIPT_TRIGGER_OHIO_URL: "https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/dev/ci/scripts/opp-trigger-operatorhubio-ci.sh"
  OPP_IMAGE: "quay.io/operator_testing/operator-test-playbooks:dev"
  OPP_PROD: 1
  OPP_MIRROR_LATEST_TAG: "latest"
  OPP_PRODUCTION_TYPE: "k8s"
  OPP_RELEASE_BUNDLE_REGISTRY: "quay.io"
  OPP_RELEASE_BUNDLE_ORGANIZATION: "community-operators-pipeline"
  OPP_RELEASE_INDEX_REGISTRY: "quay.io"
  OPP_RELEASE_INDEX_ORGANIZATION: "community-operators-pipeline"
  OPP_RELEASE_INDEX_NAME: "catalog"
  OPP_MIRROR_INDEX_REGISTRY: "quay.io"
  OPP_MIRROR_INDEX_ORGANIZATION: "community-operators-pipeline"
  OPP_MIRROR_INDEX_NAME: "catalog_prod"
  # OPP_MIRROR_INDEX_ENABLED: "0"
  OPP_MIRROR_INDEX_MULTIARCH_BASE: "registry.redhat.io/openshift4/ose-operator-registry"
  OPP_MULTIARCH_SUPPORTED_VERSIONS: "v4.5 v4.6 v4.7"
  OPP_MIRROR_INDEX_MULTIARCH_POSTFIX: "s"
  IIB_INPUT_REGISTRY_USER: "jbreza"
  OPP_REGISTRY_MIRROR_USER: "framework_automation"
  OPP_THIS_REPO_BASE: "https://github.com"
  OPP_THIS_REPO: "redhat-openshift-ecosystem/community-operators-pipeline"
  OPP_THIS_BRANCH: "main"
  OPP_REVIEWERS_ENABLED: 0


  OPP_ALLOW_FORCE_RELEASE: ${{ github.event.inputs.release }}
  OPP_REMOVE_OPERATOR_AFTER_CLONE_PATH: "${{ github.event.inputs.delete }}"
  REGISTRY_RELEASE_API_TOKEN: ${{ secrets.REGISTRY_RELEASE_API_TOKEN }}
  REGISTRY_MIRROR_PW: ${{ secrets.REGISTRY_MIRROR_PW }}
  GODEBUG: x509ignoreCN=0
  CI_OHIO_TRIGGER_TOKEN: ${{ secrets.CI_OHIO_TRIGGER_TOKEN }}
  OHIO_REGISTRY_TOKEN: ${{ secrets.OHIO_REGISTRY_TOKEN }}
  QUAY_APPREG_TOKEN: ${{ secrets.QUAY_APPREG_TOKEN }}
  QUAY_COURIER_TOKEN: ${{ secrets.QUAY_COURIER_TOKEN }}
  REPO_GHA_PAT: ${{ secrets.REPO_GHA_PAT }}

jobs:
  pr-check:
    name: "PR-traffic-light"
    runs-on: ubuntu-latest
    steps:
      - name: Block until there is no running workflow
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
      - id: prinfo
        uses: actions-ecosystem/action-get-merged-pull-request@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade pip yq
      - name: Operator traffic light
        id: op-traffic-light
        env:
          OPP_ADDED_MODIFIED_FILES: "${{ steps.files.outputs.added_modified }}"
          OPP_MODIFIED_FILES: "${{ steps.files.outputs.modified }}"
          OPP_RENAMED_FILES: "${{ steps.files.outputs.renamed }}"
          OPP_REMOVED_FILES: "${{ steps.files.outputs.removed }}"
          OPP_LABELS: "${{ steps.prinfo.outputs.labels }}"
        run: |
          echo "PR : ${{ steps.prinfo.outputs.number }}"
          echo "labels : ${{ steps.prinfo.outputs.labels }}"
          echo "OPP_LABELS=$OPP_LABELS"
          echo "Using script '$OPP_SCRIPT_ENV_URL' ..."
          bash <(curl -sL $OPP_SCRIPT_ENV_URL)
    outputs:
      opp_labels: "${{ steps.prinfo.outputs.labels }}"
      opp_test_ready: "${{ steps.op-traffic-light.outputs.opp_test_ready }}"
      opp_release_ready: "${{ steps.op-traffic-light.outputs.opp_release_ready }}"
      opp_stream: "${{ steps.op-traffic-light.outputs.opp_stream }}"
      opp_name: "${{ steps.op-traffic-light.outputs.opp_name }}"
      opp_version: "${{ steps.op-traffic-light.outputs.opp_version }}"
      opp_ci_yaml_only: "${{ steps.op-traffic-light.outputs.opp_ci_yaml_only }}"
      opp_ver_overwrite: "${{ steps.op-traffic-light.outputs.opp_ver_overwrite }}"
      opp_op_delete: "${{ steps.op-traffic-light.outputs.opp_op_delete }}"
      opp_release_delete_appreg: "${{ steps.op-traffic-light.outputs.opp_release_delete_appreg }}"
      opp_pr_title: "${{ steps.op-traffic-light.outputs.opp_pr_title }}"

  remove-k8s:
    name: "Remove / k8s"

    needs: pr-check
    if: needs.pr-check.outputs.opp_release_ready == '1'
    runs-on: ubuntu-latest
    steps:
      - name: Remove operator from index
        if: needs.pr-check.outputs.opp_op_delete == '1' && needs.pr-check.outputs.opp_name != ''
        env:
          OPP_LABELS: "${{ needs.pr-check.outputs.opp_labels }}"
        run: |
          echo "OPP_LABELS=$OPP_LABELS"
          echo "op_delete operators/${{ needs.pr-check.outputs.opp_name }}/dummy $OPP_THIS_REPO $OPP_THIS_BRANCH"
          bash <(curl -sL $OPP_SCRIPT_URL) op_delete operators/${{ needs.pr-check.outputs.opp_name }}/dummy $OPP_THIS_REPO $OPP_THIS_BRANCH
      - name: Operator release (operator version overwrite)
        if: needs.pr-check.outputs.opp_ci_yaml_only == '0' && needs.pr-check.outputs.opp_ver_overwrite == '1' && needs.pr-check.outputs.opp_name != '' && needs.pr-check.outputs.opp_version != ''
        env:
          OPP_LABELS: "${{ needs.pr-check.outputs.opp_labels }}"
          OPP_IIB_INSTALL: 0
        run: |
          echo "OPP_LABELS=$OPP_LABELS"
          echo "op_delete operators/${{ needs.pr-check.outputs.opp_name }}/${{ needs.pr-check.outputs.opp_version }} $OPP_THIS_REPO $OPP_THIS_BRANCH"
          bash <(curl -sL $OPP_SCRIPT_URL) op_delete operators/${{ needs.pr-check.outputs.opp_name }}/${{ needs.pr-check.outputs.opp_version }} $OPP_THIS_REPO $OPP_THIS_BRANCH

  operators-k8s:
    name: "Index check / k8s"
    needs: [pr-check, remove-k8s ]

    if: needs.pr-check.outputs.opp_release_ready == '1'
    runs-on: ubuntu-latest
    steps:
      - name: Index check
        id: operators
        env:
          OPP_LABELS: "${{ needs.pr-check.outputs.opp_labels }}"
          OPP_INDEX_CHECK_ONLY: 1
        run: |
          echo "OPP_LABELS=$OPP_LABELS"
          echo "'orange' operators/sync $OPP_THIS_REPO $OPP_THIS_BRANCH"
          bash <(curl -sL $OPP_SCRIPT_URL) orange operators/sync $OPP_THIS_REPO $OPP_THIS_BRANCH
      - name: Operators for sync
        run: |
          echo "Operators : ${{ steps.operators.outputs.opp_uncomplete_operators }}"
    outputs:
      opp_uncomplete_operators: "${{ steps.operators.outputs.opp_uncomplete_operators }}"

  bundles-k8s:
    name: "Bundles / k8s"
    needs: [ pr-check, remove-k8s, operators-k8s ]
    if: needs.pr-check.outputs.opp_release_ready == '1' && needs.operators-k8s.outputs.opp_uncomplete_operators != ''

    runs-on: ubuntu-latest
    steps:
      - name: Build bundles
        env:
          OPP_LABELS: "${{ needs.pr-check.outputs.opp_labels }}"
          OPP_SKIP_INDEX: 1
          OPP_FORCE_OPERATORS: "${{ needs.operators-k8s.outputs.opp_uncomplete_operators }}"

        run: |
          echo "OPP_LABELS=$OPP_LABELS"
          echo "OPP_FORCE_OPERATORS=$OPP_FORCE_OPERATORS"
          echo "orange operators/sync $OPP_THIS_REPO $OPP_THIS_BRANCH"
          bash <(curl -sL $OPP_SCRIPT_URL) orange operators/sync $OPP_THIS_REPO $OPP_THIS_BRANCH

  release-k8s:
    name: "Index / k8s"
    needs: [ pr-check, bundles-k8s ]
    if: needs.pr-check.outputs.opp_release_ready == '1' && needs.operators-k8s.outputs.opp_uncomplete_operators != ''

    runs-on: ubuntu-latest
    steps:
      - name: Index sync
        env:
          OPP_LABELS: "${{ needs.pr-check.outputs.opp_labels }}"
          OPP_FORCE_INDEX_UPDATE: 1
          OPP_FORCE_OPERATORS: "${{ needs.operators-k8s.outputs.opp_uncomplete_operators }}"

        run: |
          echo "OPP_LABELS=$OPP_LABELS"
          echo "orange operators/sync $OPP_THIS_REPO $OPP_THIS_BRANCH"
          bash <(curl -sL $OPP_SCRIPT_URL) orange operators/sync $OPP_THIS_REPO $OPP_THIS_BRANCH
